### ISSUE TITLE
Broken Screenshots on readme

### ISSUE THREAD

**Issue by Blueberryy** [Deepbluewarn/twitch_badge_collector#4]
https://github.com/Deepbluewarn/twitch_badge_collector/blob/88dfc37041b7e3937508a76e80a6e7322989c587/docs/README.md

**Comment by Deepbluewarn** [comment]
f8255f7d7b4593e21c792c92037681e2c67c8f8d
26ce8a4417ac78d519b00657696cfe39e3d100e0

done. thanks!
