### ISSUE TITLE
tbc.bluewarn.dev website is not working?

### ISSUE THREAD

**Issue by Blueberryy** [Deepbluewarn/twitch_badge_collector#5]
I tried to reach the website from pc and mobile but it gives same error
![20211017_163302](https://user-images.githubusercontent.com/36592509/137625663-a9cf673d-75cd-451c-adbc-fe086b5440e4.jpg)

**Comment by Deepbluewarn** [comment]
Overseas IP is blocked due to Cloudflare's firewall settings. This is an error I hadn't thought of at all. 
You can connect now.
