### ISSUE TITLE
VOD bug

### ISSUE THREAD

**Issue by gibson-kim** [Deepbluewarn/twitch_badge_collector#7]
![image](https://user-images.githubusercontent.com/53350590/168948374-5b7af48d-1247-4f20-8c61-93582a608515.png)

I changed my setting to have the badge collector section Up instead of Down, and much smaller than the default, but on VODs it shows the default. Can you give me a setting to disable it in VODs? Thanks.

**Comment by Deepbluewarn** [comment]
VOD chat window cannot be set up or down like live chat.

And the size of the chat window can be adjusted through the settings page of the extension.

VOD chat window is slightly different from the live chat window, so I couldn't apply all the settings.

**Comment by Deepbluewarn** [comment]
Fixed the issue in version 1.4.10. The replay chat window can be set the same as the live chat window.
